const products = [
  {
    id: 1,
    name: "COSRX Advanced Snail 96 Mucin Power Essence",
    category: "treatments",
    rating: 4.6,
    description: "Snail mucin sounds strange until you feel the texture: a thin, faintly tacky essence that layers under a heavier moisturizer without pilling.",
    details: "A cult-favorite Korean essence built around 96% snail secretion filtrate. It sits between a toner and a serum in texture, which is why it layers so easily under other products without feeling heavy.",
    features: ["96% snail secretion filtrate", "Lightweight essence texture", "100 ml bottle", "Korean skincare"],
    curatorNote: "The essence most people mean when they say 'try snail mucin' — one of the highest-rated entry points into Korean skincare.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/4yjkGGY",
    image: "images/416kUGx2rQL._SX679_.jpg"
  },
  {
    id: 2,
    name: "CeraVe Moisturizing Cream",
    category: "moisturizing",
    rating: 4.7,
    description: "A thick, fragrance-free cream built around three ceramides — the kind of moisturizer people reach for when their skin feels tight after washing.",
    details: "Developed with dermatologists, this cream leans on ceramides and hyaluronic acid to help reinforce the skin's moisture barrier. It works on both face and body, which is part of why it ends up as the 'default' moisturizer in so many routines.",
    features: ["Face and body cream", "Hyaluronic acid", "Ceramides", "Fragrance-free formula"],
    curatorNote: "Not exciting, but that's the point — this is the moisturizer people quietly repurchase for years.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/45WZLNI",
    image: "images/61EidjXUBrL._SY450_.jpg"
  },
  {
    id: 3,
    name: "The Ordinary Niacinamide 10% + Zinc 1%",
    category: "treatments",
    rating: 4.6,
    description: "A water-based niacinamide serum aimed at oil control and the look of pores — one of the most repurchased serums in skincare for its price-to-result ratio.",
    details: "Niacinamide 10% with zinc PCA 1%, formulated to help balance the appearance of oiliness and refine the look of pores. It's inexpensive enough that it's often the first 'active' someone adds to a basic routine.",
    features: ["Niacinamide 10%", "Zinc PCA 1%", "Water-based serum", "Dropper bottle"],
    curatorNote: "The serum most people try first once pores and shine become a real concern.",
    badge: "Best Seller",
    featured: true,
    amazonUrl: "https://amzn.to/4ycMbll",
    image: "images/612NxRjAoCL._SX466_.jpg"
  },
  {
    id: 4,
    name: "CeraVe Foaming Facial Cleanser",
    category: "cleansing",
    rating: 4.7,
    description: "A foaming cleanser for normal-to-oily skin that still carries ceramides and hyaluronic acid, so it doesn't leave skin feeling as stripped as most foaming washes do.",
    details: "Foams gently while cleansing, formulated with ceramides, niacinamide, and hyaluronic acid to offset the drying effect that foaming cleansers usually have.",
    features: ["Foaming gel cleanser", "Ceramides", "Niacinamide", "Pump dispenser"],
    curatorNote: "A safe, no-drama daily cleanser — the kind you buy once and stop thinking about.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4i35TeB",
    image: "images/61w1ejKsmXL._SX466_.jpg"
  },
  {
    id: 5,
    name: "CeraVe Renewing SA Cleanser",
    category: "cleansing",
    rating: 4.6,
    description: "Adds salicylic acid to CeraVe's usual ceramide-and-hyaluronic-acid base — built for rougher texture and clogged pores rather than pure hydration.",
    details: "Combines salicylic acid with CeraVe's core barrier-supporting ingredients, aimed at smoothing rough or bumpy texture without the harsh, tight-feeling aftermath of older exfoliating cleansers.",
    features: ["Salicylic acid", "Hyaluronic acid", "Niacinamide", "Rinse-off cleanser"],
    curatorNote: "The step up from a basic cleanser once texture, not just dryness, becomes the concern.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/3UzdeJ0",
    image: "images/717lRkBFR3L._SY450_.jpg"
  },
  {
    id: 6,
    name: "Neutrogena Hydro Boost Micellar Cleansing Water",
    category: "cleansing",
    rating: 4.5,
    description: "A no-rinse micellar water for lifting makeup and grime fast, without the full ritual of a double cleanse.",
    details: "Micellar water designed to break down makeup and residue with a swipe of a cotton pad — no water or rinsing required, which makes it the fallback for travel days or late nights.",
    features: ["Micellar cleansing water", "No-rinse format", "Hydro Boost line", "Bottle dispenser"],
    curatorNote: "The product for nights when a full routine isn't happening but skin still needs attention.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4x6hcGC",
    image: "images/71F5-vrxyRL._SY879_.jpg"
  },
  {
    id: 7,
    name: "COSRX Advanced Snail 92 All In One Cream",
    category: "moisturizing",
    rating: 4.5,
    description: "The cream-format companion to COSRX's snail essence — thicker, meant to seal in hydration as a final step rather than layer under other products.",
    details: "Built around 92% snail secretion filtrate in a heavier cream base, intended as a finishing moisturizer for routines already using COSRX's lighter snail mucin products.",
    features: ["92% snail secretion filtrate", "Cream texture", "Face moisturizer", "Korean skincare"],
    curatorNote: "Pairs naturally with the Snail 96 Essence, for anyone building out the full COSRX snail routine.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4xsWrWA",
    image: "images/71Msn18lZcL._SY450_.jpg"
  },
  {
    id: 8,
    name: "CeraVe PM Facial Moisturizing Lotion",
    category: "moisturizing",
    rating: 4.7,
    description: "An oil-free night lotion — noticeably lighter than most 'PM' moisturizers, which is why people keep it as their evening step even in humid climates.",
    details: "Formulated to absorb quickly without an oily finish, using hyaluronic acid, niacinamide, and ceramides to support the skin overnight without feeling greasy by morning.",
    features: ["PM facial lotion", "Oil-free formula", "Hyaluronic acid", "Niacinamide"],
    curatorNote: "For anyone who finds most night creams too heavy to actually enjoy using.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4gyzoE0",
    image: "images/61ZCYK4subL._SY741_.jpg"
  },
  {
    id: 9,
    name: "The Ordinary Hyaluronic Acid 2% + B5",
    category: "moisturizing",
    rating: 4.6,
    description: "A thin, water-based hydrating serum — one of the cheapest ways to add a hydration layer before a heavier moisturizer.",
    details: "Hyaluronic acid at multiple molecular weights plus vitamin B5, designed to sit under a moisturizer as an extra hydration layer rather than replace one.",
    features: ["Hyaluronic acid 2%", "Vitamin B5", "Water-based serum", "Dropper bottle"],
    curatorNote: "The budget hydration step people add once they realize moisturizer alone isn't cutting it.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/3UvIOaH",
    image: "images/61Se8Z9n4oL._SX466_.jpg"
  },
  {
    id: 10,
    name: "Starface Hydro-Stars Pimple Patches",
    category: "treatments",
    rating: 4.5,
    description: "Hydrocolloid pimple patches shaped like stars — functionally similar to any hydrocolloid patch, but the design is why people actually remember to use them.",
    details: "Star-shaped hydrocolloid patches that absorb fluid from blemishes overnight, using the same mechanism as clear patches — just with a shape that's become a skincare-aisle staple in its own right.",
    features: ["Hydrocolloid patches", "Star-shaped design", "Targeted application", "Refill pack"],
    curatorNote: "Effective, and unlike most spot treatments, something people don't mind being seen wearing.",
    badge: "Best Seller",
    featured: true,
    amazonUrl: "https://amzn.to/4icFew1",
    image: "images/61H-JGJPOFL._SY450_.jpg"
  },
  {
    id: 11,
    name: "PanOxyl Acne Foaming Wash",
    category: "treatments",
    rating: 4.6,
    description: "A benzoyl peroxide wash for active breakouts — a stronger, more clinical option than most drugstore cleansers, meant for treating acne rather than daily maintenance.",
    details: "A foaming benzoyl peroxide formula aimed at active acne. It's a rinse-off treatment rather than a spot product, so it targets breakouts across the whole face instead of a single blemish.",
    features: ["Benzoyl peroxide wash", "Foaming cleanser", "Pump bottle", "Acne-care routine"],
    curatorNote: "For when a gentle cleanser has stopped being enough.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4xR8NIx",
    image: "images/71I9gtceY8L._SY450_.jpg"
  },
  {
    id: 12,
    name: "The Ordinary Glycolic Acid 7% Exfoliating Toner",
    category: "treatments",
    rating: 4.5,
    description: "A liquid exfoliating toner at a beginner-friendly 7% glycolic acid — a common next step once basic cleansing and moisturizing are already dialed in.",
    details: "A leave-on glycolic acid toner meant to be swiped on after cleansing, aimed at smoothing texture and evening tone over time rather than delivering an instant result.",
    features: ["Glycolic acid 7%", "Liquid toner", "Large bottle", "Targeted skincare step"],
    curatorNote: "The toner people reach for once they're ready to actually target texture and dullness.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4qYV8wb",
    image: "images/51bC4vVdkOL._SX466_.jpg"
  },
  {
    id: 13,
    name: "Differin Adapalene Gel 0.1%",
    category: "treatments",
    rating: 4.6,
    description: "A retinoid gel that used to require a prescription — now sold over the counter for treating acne at the source rather than just calming individual breakouts.",
    details: "0.1% adapalene gel, originally prescription-only, formulated to help normalize skin cell turnover and reduce clogged pores rather than just treat existing breakouts.",
    features: ["Adapalene gel 0.1%", "Tube format", "Targeted treatment", "Acne-care routine"],
    curatorNote: "For people specifically looking for adapalene by name, not just 'a retinoid.'",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4zPOgoN",
    image: "images/61G3FDAnC8L._SY355_.jpg"
  },
  {
    id: 14,
    name: "CeraVe AM Facial Moisturizing Lotion SPF 50",
    category: "sun-care",
    rating: 4.6,
    description: "Combines a daily moisturizer with SPF 50 in one step — built for people who won't do sunscreen as a separate product.",
    details: "Broad-spectrum SPF 50 built into CeraVe's usual ceramide moisturizer base, meant to replace both a morning lotion and a separate sunscreen in one step.",
    features: ["Broad-spectrum SPF 50", "Daytime facial lotion", "Ceramides", "Pump dispenser"],
    curatorNote: "The realistic option for anyone who wants a one-step morning routine.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4zWzcWO",
    image: "images/61msVAtaNPL._SX466_.jpg"
  },
  {
    id: 15,
    name: "La Roche-Posay Anthelios Melt-In Milk Sunscreen SPF 60",
    category: "sun-care",
    rating: 4.6,
    description: "A lotion-format SPF 60 built for face and body — one of the most recommended sunscreens for people who've written off sunscreen as too greasy.",
    details: "Broad-spectrum SPF 60 in a fast-absorbing milk texture, from a line formulated for sensitive skin without the heavy or white-cast finish older sunscreens are known for.",
    features: ["Broad-spectrum SPF 60", "Lotion format", "Anthelios line", "Face and body use"],
    curatorNote: "Usually the first sunscreen recommended to someone who says they 'hate' sunscreen.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/46C2Y5q",
    image: "images/61pNJwG1erL._SY450_.jpg"
  },
  {
    id: 16,
    name: "EltaMD UV Clear Facial Sunscreen SPF 46",
    category: "sun-care",
    rating: 4.7,
    description: "A dermatologist-office staple with niacinamide and zinc oxide — priced and formulated more like a treatment product than a drugstore basic.",
    details: "An oil-free facial sunscreen combining zinc oxide, niacinamide, and SPF 46, commonly stocked in dermatology offices — a step up in both formulation and price from typical drugstore sunscreens.",
    features: ["Broad-spectrum SPF 46", "Zinc oxide", "Niacinamide", "Oil-free formula"],
    curatorNote: "The sunscreen people upgrade to once they're serious about a routine.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4zRbH12",
    image: "images/613YEAluowL._SX466_.jpg"
  },
  {
    id: 17,
    name: "BIODANCE Bio-Collagen Real Deep Mask",
    category: "masks",
    rating: 4.5,
    description: "A hydrogel mask that molds to the face like a second skin — closer to a spa treatment than the average sheet mask, which is why it's become a viral before-a-big-day pick.",
    details: "A bio-collagen hydrogel mask meant for an intensive, single-use treatment rather than everyday use — the kind of product built around a visible, immediate plumping effect.",
    features: ["Hydrogel mask", "Bio-collagen range", "Facial mask", "Single-use format"],
    curatorNote: "The mask people buy specifically for the night before an event, not for a regular rotation.",
    badge: "New",
    featured: true,
    amazonUrl: "https://amzn.to/4x6EXy9",
    image: "images/51ubxqzNGIL._SY355_.jpg"
  },
  {
    id: 19,
    name: "Mediheal Essential Mask Sheet Set",
    category: "masks",
    rating: 4.5,
    description: "A set of Korean sheet masks covering a few different skin needs — a low-effort way to try Korean sheet-masking without committing to one formula.",
    details: "A multi-mask set from one of the most recognizable Korean sheet mask brands, useful for rotating between hydration and brightening formulas without buying full-size versions of each.",
    features: ["Sheet mask set", "Hydrating formulas", "Single-use masks", "Mediheal range"],
    curatorNote: "A good starting point for anyone curious about sheet masks but unsure which one to buy first.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4qQ4lHa",
    image: "images/710pdbo9-QL._SY355_.jpg"
  },
  {
    id: 20,
    name: "Kitsch Stainless Steel Gua Sha Facial Tool",
    category: "tools",
    rating: 4.5,
    description: "A stainless steel gua sha tool for facial massage — more of a self-care ritual object than a skincare treatment on its own.",
    details: "A solid stainless steel gua sha shaped for facial contours, used to massage the face and encourage circulation — a manual tool rather than an active treatment.",
    features: ["Stainless steel", "Gua sha shape", "Facial massage tool", "Reusable design"],
    curatorNote: "Looks as good on a shelf as it feels during a five-minute massage.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4xy1BRh",
    image: "images/71y1S7ZvoSL._AC_SX466_.jpg"
  },
  {
    id: 21,
    name: "Ice Roller for Face",
    category: "tools",
    rating: 4.4,
    description: "A reusable cooling roller for calming puffiness or overheated skin — a simple mechanical tool rather than a product with active ingredients.",
    details: "A rolling head that's chilled before use, meant to reduce the appearance of puffiness and provide a quick cooling sensation, often used first thing in the morning.",
    features: ["Reusable roller", "Cooling facial tool", "Massage format", "Compact handle"],
    curatorNote: "The five-minute reset for a puffy morning face.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4x2Mzlk",
    image: "images/61VtpMKBtVL._SY355_.jpg"
  },
  {
    id: 22,
    name: "PRITECH Electric Facial Cleansing Brush",
    category: "tools",
    rating: 4.3,
    description: "A rechargeable, waterproof cleansing brush for a deeper clean than fingers alone — an entry point for anyone curious about device-based skincare without spending on a premium brand.",
    details: "A handheld, rechargeable cleansing brush designed to physically lift dirt and buildup during cleansing. It's a mechanical upgrade to a routine, not a chemical one.",
    features: ["Rechargeable device", "Waterproof design", "Vibrating brush", "Handheld format"],
    curatorNote: "For anyone who wants to try a cleansing device before committing to a pricier one.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/4yak2Lz",
    image: "images/61Q-2hny74L._AC_SX466_.jpg"
  },
  {
    id: 23,
    name: "eos Shea Better Body Lotion, Vanilla Cashmere",
    category: "body-care",
    rating: 4.7,
    description: "A Vanilla Cashmere body lotion built more around scent and everyday use than a specific skin concern — the kind people buy because they actually enjoy applying it.",
    details: "A shea-based body lotion in a generous, large-format bottle, positioned as a daily-use product where scent and texture matter as much as the ingredient list.",
    features: ["Body lotion", "Vanilla Cashmere scent", "Shea Better line", "Pump bottle"],
    curatorNote: "Body care that people actually finish the bottle of, which says more than any ingredient list.",
    badge: "Best Seller",
    featured: true,
    amazonUrl: "https://amzn.to/4yfmvEv",
    image: "images/61IQUadfGEL._SY450_.jpg"
  },
  {
    id: 24,
    name: "CeraVe SA Body Wash",
    category: "body-care",
    rating: 4.6,
    description: "Brings salicylic acid into the shower for rough patches and body texture — the body-care equivalent of a treatment cleanser rather than a basic wash.",
    details: "A salicylic acid body wash built on CeraVe's usual ceramide base, aimed at smoothing rough texture on the arms and legs rather than just cleansing.",
    features: ["Salicylic acid", "Body wash", "Ceramides", "Hyaluronic acid"],
    curatorNote: "For rough patches and bumps that a regular body wash never quite touches.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/46zdkmB",
    image: "images/51mbLoi5RIL._SY879_.jpg"
  },
  {
    id: 25,
    name: "Sol de Janeiro Brazilian Bum Bum Cream",
    category: "body-care",
    rating: 4.6,
    description: "A fast-absorbing body cream with a scent distinctive enough that people recognize it on someone else before they recognize the brand.",
    details: "A cult body cream known as much for its signature scent and packaging as for its fast-absorbing texture — the kind of product people repurchase rather than try once.",
    features: ["Body cream", "Fast-absorbing texture", "Sol de Janeiro line", "Jar packaging"],
    curatorNote: "Probably the most recognizable body cream on this list by scent alone.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/4x5PSse",
    image: "images/61VhV3+-HwL._SX466_.jpg"
  },
  {
    id: 26,
    name: "Mielle Rosemary Mint Scalp & Hair Strengthening Oil",
    category: "hair-scalp",
    rating: 4.6,
    description: "A rosemary-and-biotin scalp oil aimed at hair and scalp health rather than styling — one of the most talked-about scalp products of the last few years.",
    details: "A lightweight oil combining rosemary, mint, and biotin, massaged into the scalp rather than applied to hair lengths — built around scalp condition, not hairstyling.",
    features: ["Rosemary and mint", "Biotin", "Scalp and hair oil", "Dropper bottle"],
    curatorNote: "The scalp oil that made 'rosemary oil' a mainstream skincare-aisle term.",
    badge: "Best Seller",
    featured: true,
    amazonUrl: "https://amzn.to/46C39O8",
    image: "images/61JBgQvsWtL._SY450_.jpg"
  },
  {
    id: 27,
    name: "Olaplex No. 3 Hair Perfector",
    category: "hair-scalp",
    rating: 4.6,
    description: "A pre-shampoo bond-repair treatment — not a conditioner, but a step used before washing to work on hair structure rather than just softness.",
    details: "Used before shampooing, this treatment targets the internal bonds in hair rather than surface softness, which is why it's usually recommended after chemical or heat damage rather than as a daily product.",
    features: ["Pre-shampoo treatment", "No. 3 Hair Perfector", "Hair-care step", "Olaplex range"],
    curatorNote: "The step people add specifically after coloring, bleaching, or heat damage.",
    badge: null,
    featured: false,
    amazonUrl: "https://amzn.to/3Uv2NGu",
    image: "images/610sljWCCzL._SX466_.jpg"
  },
  {
    id: 28,
    name: "The Ordinary Vitamin C Suspension 23% + HA Spheres 2%",
    category: "treatments",
    rating: 4.5,
    description: "A high-strength, water-free vitamin C treatment — one of the more intense vitamin C formulas available, built for visible brightening rather than gentle daily use.",
    details: "23% pure L-ascorbic acid in a water-free suspension, paired with hyaluronic acid spheres. Because it's a higher concentration than most vitamin C serums, it's generally introduced gradually rather than daily from day one.",
    features: ["23% Pure L-Ascorbic Acid", "2% Hyaluronic Acid Spheres", "Brightening treatment", "Helps improve uneven skin tone"],
    curatorNote: "For anyone who has tried milder vitamin C serums and wants something stronger.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/3SIYczX",
    image: "images/51LloWpF62L._SX522_.jpg"
 },
 {
    id: 29,
    name: "medicube PDRN Pink Peptide Serum",
    category: "treatments",
    rating: 4.5,
    description: "A PDRN-and-peptide serum from the Korean 'salmon DNA skincare' trend — built around hydration and elasticity rather than a single active ingredient.",
    details: "Combines PDRN, a five-peptide complex, and niacinamide, positioned as a hydration-and-elasticity serum rather than a treatment for a specific concern like acne or dark spots.",
    features: ["Salmon DNA PDRN", "Five peptide complex", "Niacinamide", "Hydrating formula", "Helps improve uneven skin tone", "Korean skincare"],
    curatorNote: "The serum behind a lot of the 'glass skin' routines showing up in Korean skincare content.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/4x5Z7sp",
    image: "images/615DOoCI6xL._SX679_.jpg"
  },
  {
   id: 30,
    name: "medicube NAD EGF Firming Serum",
    category: "treatments",
    rating: 4.5,
    description: "A firming serum built around NAD+ and EGF — ingredients more associated with anti-aging treatments than basic hydration.",
    details: "Formulated with NAD+, EGF peptide, and a collagen complex for the face and neck, aimed at firmness and elasticity rather than surface hydration — a step up in complexity from a standard moisturizing serum.",
    features: ["NAD+", "EGF peptide", "Collagen complex", "Face and neck serum", "Helps improve skin elasticity", "Korean skincare"],
    curatorNote: "medicube's answer for people specifically asking about firmness and elasticity, not just hydration.",
    badge: "Editor's Pick",
    featured: true,
    amazonUrl: "https://amzn.to/4iOwrAu",
    image: "images/rojoskkkk.jpg"  
  },
];
